# Generated by Django 5.2.1 on 2026-02-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line1',
            field=models.CharField(default='', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Zip Code'),
        ),
    ]
