# Generated by Django 5.2.1 on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_0002_add_shipping_fee_0007_category_image'),
        ('vendors', '0002_vendor_address_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='selling_category',
            field=models.ForeignKey(
                blank=True,
                help_text='The category this vendor is allowed to sell in.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vendors',
                to='products.category',
            ),
        ),
    ]
