# Generated by Django 5.2.1 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_0002_add_shipping_fee_0007_category_image'),
        ('orders', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='products.productvariation'),
        ),
    ]
