# Generated by Django 5.2.1 on 2026-02-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_cou_vendor__bc348c_idx',
            old_name='coupons_coup_vendor_idx',
        ),
    ]
