# Generated by Django 5.2.1 on 2026-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for category', null=True, upload_to='categories/'),
        ),
    ]
