# Generated by Django 5.2.1 on 2026-02-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_shipping_fee'),
        ('products', '0007_category_image'),
    ]

    operations = [
    ]
